version: '3'
services:
  jenkins-master:
    image: harbor.thoughtworks-school.com/library/jenkins:2.60.3-alpine
    build: .
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock