version: '3'
services:
  jenkins-master:
    # image: jenkins:2.60.3-alpine
    build: .
    ports:
      - 8080:8080
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/lib/docker/:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock