kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - name: jenkins
        image: 10.0.67.135/library/jenkins:2.60.3-alpine-dind
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins
      volumes:
      - name: jenkins
        awsElasticBlockStore:
          volumeID: vol-0a67738b2efef727b
          fsType: ext4
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 32502
    targetPort: 8080
    port: 8080
    name: web
  - protocol: TCP
    targetPort: 8081
    port: 8081
    name: service
  selector:
    name: jenkins