apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: aws-jenkins-pv"
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: "100Gi" 
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-01e75004a3a8a60ef"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-jenkins-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: Deployment
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - name: jenkins
        image: 10.0.67.135/library/jenkins:2.60.3-alpine-dind
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - name: jenkins
            mountPath: /var/jenkins_home
      volumes:
      - name: jenkins
        persistentVolumeClaim:
          claimName: aws-jenkins-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 32502
    targetPort: 8080
    port: 8080
    name: web
  - protocol: TCP
    targetPort: 8081
    port: 8081
    name: service
  selector:
    name: jenkins